/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Seasons */
        get: operations["seasons_api_seasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/races": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Races */
        get: operations["races_api_races_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sessions */
        get: operations["sessions_api_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Drivers */
        get: operations["drivers_api_drivers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session-analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Analysis */
        get: operations["session_analysis_api_session_analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/qualifying-analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Qualifying Analysis */
        get: operations["qualifying_analysis_api_qualifying_analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/driver-analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Driver Analysis */
        get: operations["driver_analysis_api_driver_analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lap-telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lap Telemetry */
        get: operations["lap_telemetry_api_lap_telemetry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/track-layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Track Layout */
        get: operations["track_layout_api_track_layout_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lap-comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lap Comparison */
        get: operations["lap_comparison_api_lap_comparison_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/long-run-comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Long Run Comparison */
        get: operations["long_run_comparison_api_long_run_comparison_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/long-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Long Runs */
        get: operations["long_runs_api_long_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CompoundRanking */
        CompoundRanking: {
            /** Compound */
            compound: string;
            /** Best Average Pace Seconds */
            best_average_pace_seconds: number;
            /** Runs */
            runs: components["schemas"]["CompoundRankingEntry"][];
        };
        /** CompoundRankingEntry */
        CompoundRankingEntry: {
            /** Run Id */
            run_id: string;
            /** Position */
            position: number;
            /** Driver */
            driver: string;
            /** Stint */
            stint: number;
            /** Average Pace Seconds */
            average_pace_seconds: number;
            /** Gap To Compound Best */
            gap_to_compound_best: number | null;
        };
        /** Driver */
        Driver: {
            /** Code */
            code: string;
            /** Number */
            number: string | null;
            /** Full Name */
            full_name: string | null;
            /** Team */
            team: string | null;
        };
        /** DriverAnalysis */
        DriverAnalysis: {
            driver: components["schemas"]["Driver"];
            event: components["schemas"]["EventSummary"];
            session: components["schemas"]["SessionSummary"];
            summary: components["schemas"]["PerformanceSummary"];
            /** Laps */
            laps: components["schemas"]["LapSummary"][];
            /** Long Runs */
            long_runs: components["schemas"]["LongRun"][];
        };
        /** Drivers */
        Drivers: {
            /** Year */
            year: number;
            /** Race */
            race: string;
            /** Session */
            session: string;
            /** Drivers */
            drivers: components["schemas"]["Driver"][];
        };
        /** EventSummary */
        EventSummary: {
            /** Year */
            year: number;
            /** Name */
            name: string | null;
            /** Official Name */
            official_name: string | null;
            /** Round */
            round: number | null;
            /** Circuit */
            circuit: string | null;
            /** Country */
            country: string | null;
        };
        /** ExcludedLap */
        ExcludedLap: {
            /** Lap Number */
            lap_number: number;
            /**
             * Reason
             * @enum {string}
             */
            reason: "slower_than_107_percent_of_stint_best" | "slower_than_stint_trend" | "faster_than_stint_trend";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
        };
        /** LapComparison */
        LapComparison: {
            event: components["schemas"]["EventSummary"];
            session: components["schemas"]["SessionSummary"];
            lap_a: components["schemas"]["LapTelemetry"];
            lap_b: components["schemas"]["LapTelemetry"];
            delta: components["schemas"]["LapTimeDelta"];
        };
        /** LapSummary */
        LapSummary: {
            /** Driver */
            driver: string;
            /** Driver Number */
            driver_number: string | null;
            /** Team */
            team: string | null;
            /** Lap Number */
            lap_number: number;
            /** Lap Time Seconds */
            lap_time_seconds: number | null;
            /** Sector 1 Seconds */
            sector_1_seconds: number | null;
            /** Sector 2 Seconds */
            sector_2_seconds: number | null;
            /** Sector 3 Seconds */
            sector_3_seconds: number | null;
            /** Compound */
            compound: string | null;
            /** Tyre Life */
            tyre_life: number | null;
            /** Fresh Tyres */
            fresh_tyres: boolean | null;
            /** Stint */
            stint: number | null;
            /** Pit In */
            pit_in: boolean;
            /** Pit Out */
            pit_out: boolean;
            /** Deleted */
            deleted: boolean;
            /** Top Speed */
            top_speed: number | null;
            /**
             * Classification
             * @enum {string}
             */
            classification: "unknown" | "deleted_lap" | "out_lap" | "in_lap" | "slow_lap" | "push_lap";
        };
        /** LapTelemetry */
        LapTelemetry: {
            summary: components["schemas"]["LapSummary"];
            /** Telemetry */
            telemetry: components["schemas"]["TelemetrySample"][];
        };
        /** LapTimeDelta */
        LapTimeDelta: {
            /** Lap Time Seconds */
            lap_time_seconds: number | null;
        };
        /** LongRun */
        LongRun: {
            /** Run Id */
            run_id: string;
            /** Driver */
            driver: string;
            /** Stint */
            stint: number;
            /** Compound */
            compound: string;
            /** Lap Count */
            lap_count: number;
            /** Average Pace Seconds */
            average_pace_seconds: number;
            /** Median Pace Seconds */
            median_pace_seconds: number;
            /** Best Lap Seconds */
            best_lap_seconds: number;
            /** Worst Lap Seconds */
            worst_lap_seconds: number;
            /** Pace Dropoff Per Lap */
            pace_dropoff_per_lap: number | null;
            /** Tyre Degradation Per Lap */
            tyre_degradation_per_lap: number | null;
            /** Tyre Life Start */
            tyre_life_start: number | null;
            /** Tyre Life End */
            tyre_life_end: number | null;
            /** Laps Used */
            laps_used: number[];
            /** Laps Excluded */
            laps_excluded: components["schemas"]["ExcludedLap"][];
            /** Laps */
            laps: components["schemas"]["LongRunLap"][];
        };
        /** LongRunComparison */
        LongRunComparison: {
            event: components["schemas"]["EventSummary"];
            session: components["schemas"]["SessionSummary"];
            run_a: components["schemas"]["LongRun"];
            run_b: components["schemas"]["LongRun"];
            delta: components["schemas"]["LongRunDelta"];
        };
        /** LongRunDelta */
        LongRunDelta: {
            /** Average Pace Seconds */
            average_pace_seconds: number | null;
            /** Median Pace Seconds */
            median_pace_seconds: number | null;
            /** Pace Dropoff Per Lap */
            pace_dropoff_per_lap: number | null;
            /** Tyre Degradation Per Lap */
            tyre_degradation_per_lap: number | null;
        };
        /** LongRunEvent */
        LongRunEvent: {
            /** Year */
            year: number;
            /** Race */
            race: string;
        };
        /** LongRunLap */
        LongRunLap: {
            /** Lap Number */
            lap_number: number;
            /** Lap Time Seconds */
            lap_time_seconds: number;
            /** Tyre Life */
            tyre_life: number | null;
            /** Default Included */
            default_included: boolean;
            /** Exclusion Reason */
            exclusion_reason: ("slower_than_107_percent_of_stint_best" | "slower_than_stint_trend" | "faster_than_stint_trend") | null;
        };
        /** LongRunOverview */
        LongRunOverview: {
            event: components["schemas"]["LongRunEvent"];
            /** Session */
            session: string;
            /** Selected Drivers */
            selected_drivers: string[];
            /** Min Laps */
            min_laps: number;
            /** Fuel Correction Per Lap */
            fuel_correction_per_lap: number;
            /** Runs */
            runs: components["schemas"]["LongRun"][];
            /** Tyre Rankings */
            tyre_rankings: components["schemas"]["CompoundRanking"][];
            /** Session Tyre Ranking */
            session_tyre_ranking: components["schemas"]["SessionTyreRanking"][];
        };
        /** PerformanceSummary */
        PerformanceSummary: {
            /** Lap Count */
            lap_count: number;
            /** Timed Lap Count */
            timed_lap_count: number;
            /** Fastest Lap Seconds */
            fastest_lap_seconds: number | null;
            /** Average Lap Seconds */
            average_lap_seconds: number | null;
            /** Median Lap Seconds */
            median_lap_seconds: number | null;
            /** Best Sector 1 Seconds */
            best_sector_1_seconds: number | null;
            /** Best Sector 2 Seconds */
            best_sector_2_seconds: number | null;
            /** Best Sector 3 Seconds */
            best_sector_3_seconds: number | null;
        };
        /** QualifyingAnalysis */
        QualifyingAnalysis: {
            event: components["schemas"]["EventSummary"];
            session: components["schemas"]["SessionSummary"];
            /** Drivers */
            drivers: components["schemas"]["Driver"][];
            /** Best Laps */
            best_laps: components["schemas"]["RankedLap"][];
            /** Top Speeds */
            top_speeds: components["schemas"]["TopSpeed"][];
            /** Segments */
            segments: components["schemas"]["QualifyingSegment"][];
            /** Attempts */
            attempts: components["schemas"]["QualifyingAttempt"][];
        };
        /** QualifyingAttempt */
        QualifyingAttempt: {
            /** Driver */
            driver: string;
            /** Driver Number */
            driver_number: string | null;
            /** Team */
            team: string | null;
            /** Lap Number */
            lap_number: number;
            /** Lap Time Seconds */
            lap_time_seconds: number | null;
            /** Sector 1 Seconds */
            sector_1_seconds: number | null;
            /** Sector 2 Seconds */
            sector_2_seconds: number | null;
            /** Sector 3 Seconds */
            sector_3_seconds: number | null;
            /** Compound */
            compound: string | null;
            /** Tyre Life */
            tyre_life: number | null;
            /** Fresh Tyres */
            fresh_tyres: boolean | null;
            /** Stint */
            stint: number | null;
            /** Pit In */
            pit_in: boolean;
            /** Pit Out */
            pit_out: boolean;
            /** Deleted */
            deleted: boolean;
            /** Top Speed */
            top_speed: number | null;
            /**
             * Classification
             * @enum {string}
             */
            classification: "unknown" | "deleted_lap" | "out_lap" | "in_lap" | "slow_lap" | "push_lap";
            /** Gap To Session Best */
            gap_to_session_best: number;
            /** Segment */
            segment: string | null;
            /** Gap To Segment Best */
            gap_to_segment_best: number | null;
        };
        /** QualifyingSegment */
        QualifyingSegment: {
            /** Segment */
            segment: string;
            /** Results */
            results: components["schemas"]["SegmentResult"][];
        };
        /** Race */
        Race: {
            /** Round */
            round: number | null;
            /** Name */
            name: string;
            /** Official Name */
            official_name: string | null;
            /** Location */
            location: string | null;
            /** Country */
            country: string | null;
            /** Date */
            date: string;
        };
        /** Races */
        Races: {
            /** Year */
            year: number;
            /** Races */
            races: components["schemas"]["Race"][];
        };
        /** RankedLap */
        RankedLap: {
            /** Driver */
            driver: string;
            /** Driver Number */
            driver_number: string | null;
            /** Team */
            team: string | null;
            /** Lap Number */
            lap_number: number;
            /** Lap Time Seconds */
            lap_time_seconds: number | null;
            /** Sector 1 Seconds */
            sector_1_seconds: number | null;
            /** Sector 2 Seconds */
            sector_2_seconds: number | null;
            /** Sector 3 Seconds */
            sector_3_seconds: number | null;
            /** Compound */
            compound: string | null;
            /** Tyre Life */
            tyre_life: number | null;
            /** Fresh Tyres */
            fresh_tyres: boolean | null;
            /** Stint */
            stint: number | null;
            /** Pit In */
            pit_in: boolean;
            /** Pit Out */
            pit_out: boolean;
            /** Deleted */
            deleted: boolean;
            /** Top Speed */
            top_speed: number | null;
            /**
             * Classification
             * @enum {string}
             */
            classification: "unknown" | "deleted_lap" | "out_lap" | "in_lap" | "slow_lap" | "push_lap";
            /** Position */
            position: number;
            /** Gap To Fastest */
            gap_to_fastest: number;
        };
        /** Seasons */
        Seasons: {
            /** Seasons */
            seasons: number[];
        };
        /** SegmentResult */
        SegmentResult: {
            /** Position */
            position: number;
            /** Driver */
            driver: string;
            /** Team */
            team: string | null;
            /** Lap Number */
            lap_number: number;
            /** Lap Time Seconds */
            lap_time_seconds: number;
            /** Gap To Segment Best */
            gap_to_segment_best: number;
            /** Compound */
            compound: string | null;
        };
        /** SessionAnalysis */
        SessionAnalysis: {
            event: components["schemas"]["EventSummary"];
            session: components["schemas"]["SessionSummary"];
            /** Drivers */
            drivers: components["schemas"]["Driver"][];
            /** Fastest Laps */
            fastest_laps: components["schemas"]["RankedLap"][];
            /** Top Speeds */
            top_speeds: components["schemas"]["TopSpeed"][];
            /** Long Runs */
            long_runs: components["schemas"]["LongRun"][];
            /** Tyre Summary */
            tyre_summary: components["schemas"]["TyreStint"][];
        };
        /** SessionInfo */
        SessionInfo: {
            /** Name */
            name: string;
            /** Key */
            key: string;
            /** Date */
            date: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "race_pace" | "qualifying" | "unknown";
        };
        /** SessionSummary */
        SessionSummary: {
            /** Name */
            name: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "race_pace" | "qualifying" | "unknown";
            /** Date */
            date: string;
        };
        /** SessionTyreRanking */
        SessionTyreRanking: {
            /** Position */
            position: number;
            /** Compound */
            compound: string;
            /** Best Average Pace Seconds */
            best_average_pace_seconds: number;
            /** Gap To Session Best */
            gap_to_session_best: number | null;
            fastest_run: components["schemas"]["CompoundRankingEntry"];
        };
        /** Sessions */
        Sessions: {
            /** Year */
            year: number;
            /** Race */
            race: string;
            /** Sessions */
            sessions: components["schemas"]["SessionInfo"][];
        };
        /** TelemetrySample */
        TelemetrySample: {
            /** Distance */
            distance: number;
            /** Speed */
            speed: number | null;
            /** Rpm */
            rpm: number | null;
            /** Gear */
            gear: number | null;
            /** Throttle */
            throttle: number | null;
            /** Brake */
            brake: boolean | null;
            /** Drs */
            drs: number | null;
            /** X */
            x: number | null;
            /** Y */
            y: number | null;
        };
        /** TopSpeed */
        TopSpeed: {
            /** Driver */
            driver: string;
            /** Top Speed */
            top_speed: number;
            /** Lap Number */
            lap_number: number;
        };
        /** TrackLayout */
        TrackLayout: {
            /** Year */
            year: number;
            /** Race */
            race: string;
            /** Session */
            session: string;
            /** Official Circuit Url */
            official_circuit_url: string | null;
            /** Points */
            points: components["schemas"]["TrackPoint"][];
        };
        /** TrackPoint */
        TrackPoint: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Progress */
            progress: number;
        };
        /** TyreStint */
        TyreStint: {
            /** Driver */
            driver: string | null;
            /** Stint */
            stint: number | null;
            /** Compound */
            compound: string | null;
            /** Lap Count */
            lap_count: number;
            /** Tyre Life Start */
            tyre_life_start: number | null;
            /** Tyre Life End */
            tyre_life_end: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    seasons_api_seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Seasons"];
                };
            };
        };
    };
    races_api_races_get: {
        parameters: {
            query: {
                year: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Races"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sessions_api_sessions_get: {
        parameters: {
            query: {
                year: number;
                race: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sessions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    drivers_api_drivers_get: {
        parameters: {
            query: {
                year: number;
                race: string;
                session: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Drivers"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_analysis_api_session_analysis_get: {
        parameters: {
            query: {
                year: number;
                race: string;
                session: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionAnalysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    qualifying_analysis_api_qualifying_analysis_get: {
        parameters: {
            query: {
                year: number;
                race: string;
                session?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualifyingAnalysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    driver_analysis_api_driver_analysis_get: {
        parameters: {
            query: {
                year: number;
                race: string;
                session: string;
                driver: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverAnalysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lap_telemetry_api_lap_telemetry_get: {
        parameters: {
            query: {
                year: number;
                race: string;
                session: string;
                driver: string;
                lap: number;
                telemetry_samples?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LapTelemetry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    track_layout_api_track_layout_get: {
        parameters: {
            query: {
                year: number;
                race: string;
                session: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackLayout"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lap_comparison_api_lap_comparison_get: {
        parameters: {
            query: {
                year: number;
                race: string;
                session: string;
                driver_a: string;
                lap_a: number;
                driver_b: string;
                lap_b: number;
                telemetry_samples?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LapComparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    long_run_comparison_api_long_run_comparison_get: {
        parameters: {
            query: {
                year: number;
                race: string;
                session: string;
                driver_a: string;
                stint_a: number;
                driver_b: string;
                stint_b: number;
                min_laps?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongRunComparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    long_runs_api_long_runs_get: {
        parameters: {
            query: {
                year: number;
                race: string;
                session: string;
                drivers?: string;
                min_laps?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongRunOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
